### ISSUE TITLE
Method creation/modification/deletion tracking to suggest recently changed methods for "self"

### ISSUE THREAD

**Issue by numberpi** [HPI-SWA-Lab/BP2014H1#11]
- [x] process method additions
- [ ] process method deletions
- [ ] invalidate list (idle, timestamp, image closed ...)
